export const COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Oman",
  "Bahrain",
  "Canada",
  "Australia",
  "Singapore",
  "Malaysia",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Netherlands",
  "Ireland",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Bangladesh",
  "Pakistan",
  "Sri Lanka",
  "Nepal",
  "Philippines",
  "Indonesia",
  "New Zealand",
  "Other",
] as const;
